export const EMPLOYEES_ERROR_CLEAR = 'EMPLOYEES_ERROR_CLEAR';
export const EMPLOYEES_SUCCESS_CLEAR = 'EMPLOYEES_SUCCESS_CLEAR';
export const EMPLOYEES_REQUEST = 'EMPLOYEES_REQUEST';
export const EMPLOYEES_FAILURE = 'EMPLOYEES_FAILURE';
export const EMPLOYEES_UPLOAD_SUCCESS = 'EMPLOYEES_UPLOAD_SUCCESS';
